name: Feature Request
description: Request for new Feature
title: "[Feature Request]: "
labels: ["features", "request"]
assignees:
  - florintanasa
body:
  - type: markdown
    attributes:
      value: |
        Welcome to the Taxonomy - Wishlist
  - type: textarea
    id: feature-description
    attributes:
      label: Feature description
      description: What would you like to see?
      value: |
        As a ...
        I want to ...
        So that I can ...
    validations:
      required: true