-- alter table TAXONOMY_TAXONOMIC_UNITS add column KINGDOM_ID uuid ^
-- update TAXONOMY_TAXONOMIC_UNITS set KINGDOM_ID ='504b068c-78ab-2d41-79d3-5f2658d92f96';
-- alter table TAXONOMY_TAXONOMIC_UNITS alter column KINGDOM_ID set not null ;
-- alter table TAXONOMY_TAXONOMIC_UNITS add column KINGDOM_ID uuid not null ;
