alter table TAXONOMY_TAXONOMIC_UNITS add constraint FK_TAXONOMY_TAXONOMIC_UNITS_ON_KINGDOM foreign key (KINGDOM_ID) references TAXONOMY_KINGDOMS(ID);
create index IDX_TAXONOMY_TAXONOMIC_UNITS_ON_KINGDOM on TAXONOMY_TAXONOMIC_UNITS (KINGDOM_ID);
