alter table TAXONOMY_TAXON_UNIT_TYPES add constraint FK_TAXONOMY_TAXON_UNIT_TYPES_ON_KINGDOM foreign key (KINGDOM_ID) references TAXONOMY_KINGDOMS(ID);
create unique index TAXON_UT_INDEX on TAXONOMY_TAXON_UNIT_TYPES (KINGDOM_ID, RANK_ID) where DELETE_TS is null ;
create index IDX_TAXONOMY_TAXON_UNIT_TYPES_ON_KINGDOM on TAXONOMY_TAXON_UNIT_TYPES (KINGDOM_ID);
